obstacle_range: 2.5 # 2.5
raytrace_range: 5.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
robot_radius: 0.3 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.1 # 3.0

#plugins: []

#observation_sources: point_cloud_sensor
observation_sources: laser_scan_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mybot/laser/scan2, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: os1_sensor, data_type: PointCloud2, topic: /os1_cloud_node/points, marking: true, clearing: true, max_obstacle_height: 300, min_obstacle_height: 50}
